### ISSUE TITLE
c/cpp support

### ISSUE THREAD

**Issue by ayoubelmhamdi** [lukas-reineke/cbfmt#20]
[uncrustify](https://github.com/uncrustify/uncrustify) is a formatter for c/cpp write by `rust`

`.cbfmt.toml`
```toml
[languages]
rust = ["rustfmt"]
c= ["uncrustify -q -l C --no-backup"]
```
`md.md`
<pre>

# Test
```c
int main () { int = 2; int b = 3; }
```
</pre>

# TRY
```bash
❯ cbfmt md.md
[Fail]: md.md

[0/1] files are formatted correctly.
```
> file Fail to formatted

but `uncrustify` work from `command line`

```bash
$ uncrustify -q -l C --no-backup md.md
cat md.md
```
`cat md.md`
<pre>
#Test
` ` ` c
int main() {
    int = 2;
    int b = 3;
}
` ` `
</pre>
