### ISSUE TITLE
Does not handle spaces in arguments well

### ISSUE THREAD

**Issue by UtkarshVerma** [lukas-reineke/cbfmt#36]
I'm trying to have `cbfmt` autoformat my C code blocks using `clang-format` with the following config:

```toml
[languages]
c = ["clang-format -style=\"{BasedOnStyle: Google, IndentWidth: 4, UseTab: Never, TabWidth: 4}\""]
```

However, it seems to split args on spaces without respecting the escaped quote. `clang-format` thinks that it has received 6 filenames which yields the error:

```console
$ cbfmt -w test.md
[Error]: test.md:3 [c] -> [clang-format]
No such file or directory
No such file or directory
No such file or directory
No such file or directory
No such file or directory
No such file or directory
No such file or directory


[0/1] files were written.
```

Here's my test markdown file:
````md
Hello

```c
struct MailStructure {
  unsigned int data : 18;  // Assuming data is 18 bits
  unsigned int reserved : 10;
  unsigned int channel : 4;
};
```
````
